language: generic
sudo: required
dist: trusty
env:
  matrix:
  - ARCH=armv6
  - ARCH=x86
  global:
  - secure: fbLqvHTki6IJCnqwaXMmKX+9EZak0U2VvwNwiTHptQXQZm5dhUF13VQIrgekCjjrNnaOiQdTRYdTyH+p85xRq8hKsvCDVw6V1VgN+3nCRFk+zkGKjqGQ7qIHSrbbJKzl1EAJzb4i5gjtmSoRokFaHnbxMEQ9iyaqLkRA/30yiRfTAnMYqFnbyW9Wl5sfgOcGyiLEXW3VXVMAyOy4n4zfeY4zXq7FD/nRK968sdv/q2yWIPShKAPeAd6ol3+co+8GXBvw2XjodcPmvlw8hmtI/GaQfxr+c+sfwFAaD3e7LN3GCUYW/IV/l83u9eOj7GJ+lOqFdnMRXuRb3xPPlHnhPC/MEbEkARyXieORt5wqNaPK46zRGxSO7N9phS/SZmJLt6YdZEq+A/BjDrgocdERngPAGPEmhhEARHmqQsCim7nAhT6RktzwIjA4Jpbg2DvjmfR17hJ6jUk6MrXsxL7hMnKlDK5ACHBTNka/hrZL7+qVbRNUrPUq5t/fxLRFI5rLQb28W5YQ4rkGMSwWx9WDf7qjtXVH+tv/V4P9CVJIKuMPc5dEkS4FBhYvPkSMY6Oz5K0PZ7eiUO5hGrV0FixbS6dmr/5T+mUeHCUTVJvXc973MghpoWyBM71blkuCS333bvbs7o2R0GjeWkEusKvlb4tu8HgZlKNhXqKq5wJxwfU=
  - secure: V7oFMoWSeKvIzAr/rTldjztwXuKEGVaCD4u+UwFjYW8VkHfb15o2DeO9cPE3IX79mGZPxs0vpRVdyc8idfJ6GBKSTriQrsGqvhhA+/dtplM8Xob6Mkk4Dd/xS88m+iaVqf0bDYjMI5Ghbqwqax5MUmMqcO//f67vgZvv0o5WDDRAOcym5sszpxZX4SwF49tVIlqWW71HPjunmDNIRpfbhWJuWrA6LJTFLv69j7FGCkY0fkcYsglVV+Gyyr7J+vK9gDHLSo8xXkEEqwlNFwAVVZV/jf+BUp16KVS0YJFLpgJxYX4J7PHKSNXroph+Q2A7CHas4/b+4wewSrXw2KbzxUFiDqmzn0t1xdj7qqwphNkoB6lpZEGuMtrPJ6f7MIFVlzIyxT3Ba2+ejC8PcunKOagX2jkW4DfXGOec6pUqor4xecr+pCyZ5chLjGwqZric2b6D5QehUlFzS2kB/ibv426IHWzWwKzoJCkpbF8SujObDN1Hgqs/Q9iA+CnrG1fd8fu+FXTyHlj4hYEx8abQZTX5tu6GLOwTZZGhIHQYemjvuJ26I3CMSSG6bkNNK9O3hy98hj2wDCdbvpQPd0XnMQsYSPg+TtfWGnfblFAzAk7g++tS3AptaH+tuGcIH7d56X+ob5H4Ud/UPisHKbUKL/zhHPjiDudMlteeiF3g3Zs=
services:
- docker
branches:
  only:
  - master
  - develop
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
install: true
script:
- "./build $ARCH"
deploy:
- provider: script
  script: bash deploy.sh $DOCKER_USER $DOCKER_PASS $ARCH $TRAVIS_BRANCH
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master|develop$"
- provider: script
  script: bash deploy.sh $DOCKER_USER $DOCKER_PASS $ARCH $TRAVIS_TAG
  on:
    tags: true
    all_branches: true
