language: generic
sudo: required
dist: trusty
env:
  matrix:
  - ARCH=armv6
  - ARCH=x86
  global:
  - secure: itoth+fc9yQjuuSugiYEo3cNM43jum+aYfbq5mmiA8osEMHQNhbphWAYX+R9DiG+QpVLhqMGyrLr7+houtjVgMvcG98c4g2AyNwnBeV+3zopFbs6Q/h0Q8VgACSo5qK2cs15zmHYrG4D4K7qLX5Q1aGd3yjnrhc3NJEWaTgqKsAziKQIcVvd6gKGFQXVMkq/v+pSfZ9rhElb6uSs3JgblyuLgIf8vV0RtlMtavUHEgIRVnuMrmlv5e720tbqeggQDSFhuhnfsrunVZOciwpSoM30L/WWhCs/6JyuFhxgcTCsZ7EJd1yKDLZhTSMNMD4rGG0mbBnU6sq4vTSVMaBxLKqyG3W+A4A+A/wlHJsaTOIK8USDIrm4L/HtzW+lqG5dwKlupIFZbJWNzIl+qhyTBTiUkzsbTY+4avsLVTTS7oi5ZAB98+x0xxru/Hh1MVv5TR4N/Y3FM+yw+ntloTVdbAXhofSOQFm1K2IXDw//DHqwooTCKqvGwzhwDeL3WNUvcJDhYzOBr2+OD+dLJWgzMBBRuRE3a9qdpRZ+2Wt7yrj8Kp3d8hL2fgtbmlZS9Hw6eKeQf7b3GFLhMO5m50v32m0EDVbDxzUV8bHSGA3FPbWztN1QuDlh+oJXmM4HBNVCEgzcORznq0DYWtHYdejb/VTmpDgXawQV3k5UAIxwmts=
  - secure: CtD9rT4Gz1htcHWmeL71ymxG1tfx5UZPiFg9pYkaGfX3bIkCzUo3XfKGT51TlhLfwoz5po/LIzT0wIrptp2MAg5SJHwNSHwqKfEA90zygKXAUN4tM3RcierzbSBv9HncaJXNs2F5SZ537yGrc2dFeNOJ8YWrfkgxDssp03TfpD8VF6MDQkg+Ax94CO2AbTs5qRbgn29534jDMShaHMYZatL1fWJDcYYnMUMgWk6KulQBQlMGVPvTPTR/ZStzYivpA9FzPfYR0LljovTyw0XFI9pXawsCbDM4jl/1JqhDvem7B3fQzauC4Ki4OThpmaPmtQAxwKqAD9dGGlbGNtBt9PPBBOmIaFyhFv2UxyXYd5+g6Ky2fbgxh0oKmzgef8mlo1xv58vC+v6Rl8sB9XRhOxJyJtCJ/YYy4HhdRwa6mJDXN/8RnaaCgSiOfVs2RsUH8pW9Ym4vWtBcbFXKTqgKOUo5htLKDisMNK9mUhDVhlj4ifDbaVit3CBMJ69dUAnPB/AKftAiIbeRC8vpe7nhfMO6uvlrQq0JLzQFHDur7mz1JD3I/n1ZFbeRncFs4vNfbKZRSx8KglWnnk6gbxSGitLVF/rZ2uLsLkiMi8NT0Sr7ARoN4z3dgP3ihJQnPeWqRZMRaob3g+q9fj6KU+o0fk/BfQy65HAkoFLDwN5hapc=
services:
- docker
branches:
  only:
  - master
  - develop
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
install: true
script:
- make mk-image ARCH=$ARCH
- make mk-deployment VERSION=$TRAVIS_TAG
deploy:
- provider: script
  script: make pushtohub USER=$DOCKER_USER PASS=$DOCKER_PASS ARCH=$ARCH TAG=$TRAVIS_BRANCH
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master|develop$"
- provider: script
  script: make pushtohub USER=$DOCKER_USER PASS=$DOCKER_PASS ARCH=$ARCH TAG=$TRAVIS_TAG
  on:
    tags: true
    all_branches: true
- provider: releases
  prerelease: true
  skip_cleanup: true
  file_glob: true
  file: "./*.zip"
  on:
    tags: true
    all_branches: true
    api_key:
      secure: DOKXkyRbTC2i9IFimK2wIGiCFnx0YvdAeAN5huwz0+S+tlFd/xfoeaxvmCq2V5z9HsuULYE6MwGtETzn3UVo2g5fdN+csOWMQzB46BD/M0pT9fajxmpbOxDmWMN2oiBce8qgnC9ktsW1WBRDzVHzrA5keAYiu/mGxo+X4sv/6TTr8tu25pcfZDwjGFEZb7+IYxbv/sXcTcOzbY6MiqFFrfwcMW9JsJJ2GxLKRwBvURZ7u5GDNwLC3GvrUPxcZ+Rs/ZDdOSMbi0PeAyGh2GDrQLCibuZWMeGJ4OKSbNDEf9bmfZj9XCcHlxWZDXVHp7N5oCgtL/2dRFlzFMq4aZd6RUrMTggF9+gdx7LawuRwAS/2oX3kaPKkMxFspj2RMQOCVyMqjc+MBTc6jV+PHmpP+M2L4PX6XXrRMqDY5H7k6yHPZmhOnARZQza8weQ9sBTn5KPDZ2ehkcRoVvOdZWaT0BQd57Qoyp05Q9fn3TGKj2nQ300v2aqctyOrGIE1F6k0nEKg3PBnmDm+U2skYaDS7Yq/dbM0bqsjG8CUivk1yj/8/3KrEge9Y2me5phPj7GspmsRwM0lsv3mZuslC1KvzInan+Fn/bl8Q/89iNpcRIDCKnviwQeXqKdy2ppJ1vWI6wVTUpFTvg3SoOctwXbXSgew14TRD6J2wON3BReP+Qk=
